name: action-yaml
run-name: action yaml - ${{inputs.target_environment}}
on: 
  workflow_dispatch:
    inputs:
      target_environment:
        description: 'Target environment for deployment'
        type: choice
        options:
            - dev
            - prod
        

env:
    working_dir: ./action-react/react-app
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Build react app
              uses: ./.github/actions/composit-cache-dep
              with:
                node-version: '20.x'
                working-directory: ${{ env.working_dir }}
                target-environment: ${{ inputs.target_environment }}
            - name: test
              run: npm test
              working-directory: ${{ env.working_dir }}
            - name: Build
              run: npm run build
              working-directory: ${{ env.working_dir }}
