name: action-yaml
on: workflow_dispatch
env:
    working_dir: ./action-react/react-app
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Build react app
              uses: ./.github/actions/composit-cache-dep
              with:
                node-version: '20.x'
                working-directory: ${{ env.working_dir }}
            - name: test
              run: npm test
              working-directory: ${{ env.working_dir }}
            - name: Build
              run: npm run build
              working-directory: ${{ env.working_dir }}
