name: building_blocks
on: workflow_dispatch
jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world action step
        run: echo "Hello, world!"
  echo-hello-again:
    runs-on: ubuntu-latest
    steps:
      - name: Successful step
        run: |
            echo "i am successful"
            exit 0
      - name: Hello again action step
        run: echo "Hello again, world!"