name: docker-actions
on: 
  workflow_dispatch:
    inputs:
        url:
            description: 'URL to ping'
            required: true
            type: choice
            options:
                - https://www.google.com
                - https://www.invalid-hjj.com
                - karthik.com
        max-retries:
          description: Maximum number of retries before exiting
          default: '10'
          required: false
        delay:
          description: Delay in seconds between retries
          default: '5'
          required: false
jobs:
  ping-url:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Ping URL using Docker
        uses: ./.github/actions/docker-ping-url
        with:
          url: ${{ inputs.url }}
          max-retries: ${{ inputs.max-retries }}
          delay: ${{ inputs.delay }}
          
