name: include-example
on: workflow_dispatch
jobs:
    include-outputs:
        runs-on: ubuntu-latest
        name: ${{ matrix.color }} - ${{ matrix.size }} - ${{ matrix.shape }} - ${{ matrix.opacity }}
        strategy:
            fail-fast: false
            matrix:
                color: [red, green]
                size: [small, large]
                shape: [circle, square]
                include:
                    - opacity: 50
                    - color: red
                      opacity: 75
                    - shape: circle
                      opacity: 100
                    - color: red
                      shape: triangle 
                exclude:
                    - opacity: 75
        steps:
            - name: Dummy step
              run: echo "This is a dummy step for ${{ matrix.color }} - ${{ matrix.size }} - ${{ matrix.shape }} - ${{ matrix.opacity }}"